### ISSUE TITLE
does it work under raspberry pi 3 libreelec?

### ISSUE THREAD

**Issue by gilles0606** [gonzalo-hvega/pvr.iptvsimple#4]
hi,

this plugin works under libreelec?
do you have information to test this?

big thanks

**Comment by 7FM** [comment]
Hi,
I have created a own repo which merges this repo with the original one's to be hopefully compatible with the latest kodi version. So I can simply use it for compiling LibreELEC you simply have to change the PKG_URL in packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk to:
PKG_URL="https://github.com/7FM/pvr.iptvsimple/archive/$PKG_VERSION.tar.gz"
and change the PKG_VERSION and PKG_SHA256 accordingly. If i remember correctly you will also need to modify the ffmpeg package.mk and add a package.mk for avconv...

**Comment by slucas97** [comment]
Hello Gonzalo,

After the gilles0606's coments, did you make any way easier for install this addon in LibreElec? I would like to test in LibreElec with Kodi Leia and Raspberry Pi 3 B, but I am a newbie and there is no tools to compile in LibreElec 9.1.

Congrats by your tool, friend! :) Thanks a lot!
